### ISSUE TITLE
Specifying ip_address incompatible with exact_count > 1

### ISSUE THREAD

**Issue by cholick** [CenturyLinkCloud/clc-ansible-module#10]
I would expect to be able to specify an array of IP addresses to use in conjunction with exact count, for example:

```

---
- name: deploy ubuntu hosts at CLC (Yay!)
  hosts: localhost
  gather_facts: False
  connection: local
  tasks:
    - name: Ensure that exactly 2 Ubuntu servers are running in Default Group with specified ips
      clc_server:
        location: qa3
        name: test
        network_id: 90a9ahfiahsdi4598hasd
        ip_address:
          - 192.168.1.1
          - 192.168.1.2
        template: ubuntu-14-64
        exact_count: 2
        group: 'Default Group'
        count_group: 'Default Group'
```

The server creation logic, though, simply passes the full block ip addresses to the API. The behavior I would expect would be that the check for existing servers reconciles both the count of the number of servers and their ip addresses, and creates/deletes accordingly.
