### ISSUE TITLE
Unable to use clc_server_fact

### ISSUE THREAD

**Issue by pkvenu** [CenturyLinkCloud/clc-ansible-module#30]
I upgrade the clc_ansible_module to the latest version to gather server facts but errors with the following messages: 

```
ERROR! no action detected in task. This often indicates a misspelled module name, or incorrect module path.

The error appears to have been in '/Users/pawan/Documents/projects/ic_clc_provisioning/roles/kickstart/tasks/main.yml': line 5, column 3, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:


- clc_server_fact:
  ^ here
```

Below is my playbook.

```

---

# System Server Facts

- clc_server_fact:
    server_id: "{{ hostvars[item]['clc_id'] }}"
  with_items:
    - "{{ groups['newservers'] }}"
  register: clc_server_info

# Packages to Add

- name: "Install Package Group"
  yum: name="@core" state=latest

- name: "Install other software"
  yum: pkg={{item}} state=installed
  with_items:
    - sysstat
    - ntp
    - net-snmp
    - logwatch
    - libselinux-python
```

```
sh-3.2# pip show clc-ansible-module

---
Metadata-Version: 1.1
Name: clc-ansible-module
Version: 1.1.6
Summary: Centurylink Cloud Ansible Modules
Home-page: http://www.centurylinkcloud.com
Author: CenturyLink Cloud
Author-email: WFAAS-LLFT@centurylink.com
License: CTL Corporate License
Location: /Library/Python/2.7/site-packages
Requires: clc-sdk
Classifiers:
  Development Status :: 3 - Alpha
  Programming Language :: Python
Entry-points:
  [console_scripts]
sh-3.2# 
```

**Comment by markramach** [comment]
This generally means that your ansible library path is incorrect.

```
 $ pip show clc-ansible-module
 ---
 Metadata-Version: 1.1
 Name: clc-ansible-module
 Version: 1.1.6
 Summary: Centurylink Cloud Ansible Modules
 Home-page: http://www.centurylinkcloud.com
 Author: CenturyLink Cloud
 Author-email: WFAAS-LLFT@centurylink.com
 License: CTL Corporate License
 Location: /Library/Python/2.7/site-packages
 Requires: clc-sdk
 Entry-points:
   [console_scripts]

 $ export ANSIBLE_LIBRARY=/Library/Python/2.7/site-packages/clc_ansible_module
 $ export CLC_V2_API_USERNAME=<username>
 $ export CLC_V2_API_PASSWD=<password>
 $ ansible localhost -m clc_server_fact -a "server_id=UC1WFTCWRDPRS21"

 localhost | SUCCESS => {
     "changed": false, 
     "server": {
         "changeInfo": {
             "createdBy": "mark.ramach.wftc", 
             "createdDate": "2016-04-04T17:18:23Z", 
             "modifiedDate": "2016-04-04T17:21:45Z"
         }, 
 ...
```

**Comment by pkvenu** [comment]
Hi Mark, 

I was able to get the facts when using localhosts by running the following commands. 

```
$ export ANSIBLE_LIBRARY=/Library/Python/2.7/site-packages/clc_ansible_module
 $ export CLC_V2_API_USERNAME=<username>
 $ export CLC_V2_API_PASSWD=<password>
 $ ansible localhost -m clc_server_fact -a "server_id=UC1ICN3TEST0158"
```

When I run it using a playbook example like : 
`ansible-playbook` -i hosts init.yml ` it errors stating requests library is required. When i checked /Library/Python/2.7/site-packages/ i see the requests library installed.  

*_Error Message: *_

```
ASK [kickstart : Retrieve Server Facts] ***************************************
task path: /Users/pawan/Documents/projects/clc/roles/kickstart/tasks/main.yml:5
<10.141.119.20> ESTABLISH CONNECTION FOR USER: root on PORT 22 TO 10.141.119.20
<10.141.119.20> EXEC /bin/sh -c 'mkdir -p "` echo $HOME/.ansible/tmp/ansible-tmp-1461691565.6-8027163538744 `" && echo "` echo $HOME/.ansible/tmp/ansible-tmp-1461691565.6-8027163538744 `"'
<10.141.119.20> PUT /tmp/tmp_u7Fo8 TO /root/.ansible/tmp/ansible-tmp-1461691565.6-8027163538744/clc_server_fact
<10.141.119.20> EXEC /bin/sh -c 'LANG=en_US.UTF-8 LC_ALL=en_US.UTF-8 LC_MESSAGES=en_US.UTF-8 /usr/bin/env python /root/.ansible/tmp/ansible-tmp-1461691565.6-8027163538744/clc_server_fact; rm -rf "/root/.ansible/tmp/ansible-tmp-1461691565.6-8027163538744/" > /dev/null 2>&1'
fatal: [10.141.119.20]: FAILED! => {"changed": false, "failed": true, "invocation": {"module_args": {"credentials": false, "server_id": "UC1ICN3TEST0158"}, "module_name": "clc_server_fact"}, "msg": "requests library is required for this module"}
```

```
host: 
[newservers]
10.141.119.20

main.yml
---
# System Server Facts

- name: "Retrieve Server Facts"
  clc_server_fact:
    server_id: UC1ICN3TEST0158
  register: clc

```

**Comment by markramach** [comment]
In this case your task is executing on 10.141.119.20. So requests must be installed on that host.

**Comment by markramach** [comment]
Here is an example that executes the clc_server_fact module on localhost and set variables on in-memory inventory.

``` yaml
---
- name: setup inventory
  hosts: localhost
  gather_facts: False
  connection: local

  vars:
    server_id: UC1ICN3TEST0158

  tasks:

    - name: Lookup Server
      clc_server_fact:
        server_id: "{{ server_id }}"
        credentials: true
      register: server_fact

    - name: Add new servers to in-memory inventory.
      add_host:
        name={{ server_fact['server']['name'] }}
        ansible_ssh_host={{ server_fact['server']['details']['ipAddresses'][0]['internal'] }}
        ansible_ssh_user={{ server_fact['server']['credentials']['userName'] }}
        ansible_ssh_pass={{ server_fact['server']['credentials']['password'] }}
        groups=target_servers

- name: install software
  hosts: target_servers
  tasks:
  - shell: echo {{ name }}
```

**Comment by pkvenu** [comment]
Thanks mark. Just one more question. Does that mean that we need to also set the CLC_V2_API_PASSWD, and CLC_V2_API_USERNAME in the remote host 10.141.119.20 for which i am gathering facts. I am receiving an error in the remote host. 

`fatal: [10.141.119.20]: FAILED! => {"changed": false, "failed": true, "invocation": {"module_args": {"credentials": false, "server_id": "UC1ICN3TEST0158"}, "module_name": "clc_server_fact"}, "msg": "You must set the CLC_V2_API_USERNAME and CLC_V2_API_PASSWD environment variables"}`

**Comment by pkvenu** [comment]
Thanks Mark for the help.

**Comment by steventarver** [comment]
Thanks for that excellent example Mark. From it, I built an adhoc playbook that allows the user to specify both servers and roles at playbook execution time as opposed to relying on inventory groups and tagging. Sharing since it seems pretty useful for testing playbooks and touching up servers.

``` yaml
---
# clc-adhoc: apply adhoc roles to adhoc servers
#
# Uses clc-ansible-module and clc-python-sdk to gather clc facts about servers,
# adds those servers to inventory, and then applies roles to those servers.
#
# Hosts and roles may be specified on the command line; if not, user is prompted.
# Hosts and roles may be scalar or list
#   UC1DBDVSECEVT02
#   ['UC1DBDVSECEVT02','UC1DBDVSECEVT01']
#
# Examples:
#   # user prompted for both host names and roles
#   ansible-playbook -i /dev/null clc-adhoc.yml
#
#   # specify one server, user prompted for roles
#   ansible-playbook -i /dev/null clc-adhoc.yml -e "hosts=UC1ALISTEST02"
#
#   # specify server list, user prompted for roles
#   ansible-playbook -i /dev/null clc-adhoc.yml -e "hosts=['UC1ALISTEST02','UC1ALISTEST01']"
#
#   # specify server list, specify role list
#   ansible-playbook -i /dev/null clc-adhoc.yml -e "hosts=['UC1ALISTEST02','UC1ALISTEST01'] roles=['role1','role2']"
#
# notes:
# - use inventory /dev/null to ensure only specified hosts are in inventory
#
- name: setup inventory
  hosts: localhost
  gather_facts: False
  connection: local

  vars_prompt:
    - name: "hosts"
      prompt: |
        Enter hosts as a string: UC1ALISTEST02, or quoted string list: ['UC1ALISTEST02','UC1ALISTEST01']
        Which servers would you like to target?
      private: no
      when: hosts is undefined

  tasks:
    - name: lookup clc server facts
      clc_server_fact:
        server_id: "{{ item }}"
        credentials: true
      with_items: "{{ hosts }}"
      register: server_facts

    - name: add discovered server(s) to in-memory inventory
      add_host:
        name={{ item['server']['name'] }}
        ansible_ssh_host={{ item['server']['details']['ipAddresses'][0]['internal'] }}
        ansible_ssh_user={{ item['server']['credentials']['userName'] }}
        ansible_ssh_pass={{ item['server']['credentials']['password'] }}
        groups=target_servers
      with_items: "{{ server_facts.results }}"

- name: apply roles
  hosts: target_servers
  gather_facts: True

  vars_prompt:
    - name: "roles"
      prompt: |
        Enter roles as a string > my-role, or quoted string list > ['my-role1','my-role2']
        Which roles would you like to apply?
      private: no
      when: roles is undefined

  # you must specify all possible roles here
  roles:
    - { role: my-role1, when: "'my-role1' in roles" }
    - { role: my-role2, when: "'my-role2' in roles" }
```
