### ISSUE TITLE
Set Custom Fields fails with error 

### ISSUE THREAD

**Issue by pkvenu** [CenturyLinkCloud/clc-ansible-module#47]
I am trying to add customs fields when creating a server and it returns back with error. It only happends when i try to add custom fields.

> msg": "Unable to create the server: leo. {\"message\":\"An error has occurred.\"}"}

```
- name: "Deploy centos servers"
  clc_server:
    cpu: "{{cpu}}"
    memory: "{{memory}}"
    os_type: "{{os_type}}"
    storage_type: "{{storage_type}}"
    template: "{{template}}"
    password: "{{server_password}}"
    additional_disks:
      - { path: "{{disk_path}}", sizeGB: "{{disk_size}}" , type: "{{disk_type}}" }
    custom_fields:
      - {id: "owner", value: "pawan"}
      - {id: "role", value: "relay"}
    group: "{{group.group.name}}"
    name: "{{server_name}}"
    exact_count: 2
    count_group: "{{group.group.name}}"
  register: clc
  tags: ['provisioning']
```

If i remove the custom fields, I am able to provision the server without any problem. 

Thanks,
Pawan Vengopal

**Comment by jwcolbert** [comment]
The error is coming back directly from the CenturyLink Cloud API. This is because the API is not expecting "id" to be a friendly name. It is expecting to receive the actual id of a custom field that has been predefined through the control portal.

For example, I have custom field defined through the control portal with the friendly name "test". In order to set a value for that custom field on a newly provisioned server, below would be my task:

```
- name: Build New Servers if Needed
  clc_server:
    name: websrv
    template: ubuntu-14-64
    password: "{{ serverpass.stdout }}"
    exact_count: 1
    group: "{{ server_group }}"
    count_group: "{{ server_group }}"
    custom_fields:
      - {id: "443f642eb9c74f5bace5eb20a4e80451", value: "some_value"}
```

At the below link is the documentation regarding querying the API to find the id for your various custom fields. 
https://www.ctl.io/api-docs/v2/#custom-fields
